<?php

namespace Database\Seeders;

use App\Models\Roadmap;
use Illuminate\Database\Seeder;

class RoadmapSeeder extends Seeder
{
    public function run(): void
    {
        $roadmaps = [
            [
                'user_id' => 2, // Budi
                'skill_id' => 1, // Laravel
                'title' => 'Belajar Laravel dari Nol sampai Mahir',
                'description' => 'Roadmap lengkap untuk mempelajari Laravel dari dasar hingga level advanced, mencakup routing, Eloquent, API, dan deployment.',
                'level' => 'Beginner',
                'hours_per_day' => 3,
                'target_deadline' => '2026-05-20',
                'tujuan_akhir' => 'Mampu membuat REST API lengkap dengan Laravel dan deploy ke production server.',
                'status' => 'active',
                'ai_raw_response' => json_encode(['message' => 'Roadmap generated by AI for Laravel learning path from beginner to advanced level.']),
            ],
            [
                'user_id' => 3, // Siti
                'skill_id' => 2, // React.js
                'title' => 'Menguasai React.js untuk Frontend Modern',
                'description' => 'Panduan belajar React.js step-by-step mulai dari komponen dasar, hooks, state management, hingga Next.js.',
                'level' => 'Intermediate',
                'hours_per_day' => 2.5,
                'target_deadline' => '2026-06-15',
                'tujuan_akhir' => 'Mampu membangun SPA kompleks dengan React dan mengintegrasikannya dengan backend API.',
                'status' => 'active',
                'ai_raw_response' => json_encode(['message' => 'Roadmap generated by AI for React.js frontend development.']),
            ],
            [
                'user_id' => 4, // Andi
                'skill_id' => 5, // Flutter
                'title' => 'Flutter Mobile Development Roadmap',
                'description' => 'Roadmap untuk mempelajari Flutter dari dasar widget hingga state management dan integrasi API.',
                'level' => 'Beginner',
                'hours_per_day' => 2,
                'target_deadline' => '2026-07-01',
                'tujuan_akhir' => 'Mampu membuat aplikasi mobile cross-platform dan publish ke Play Store.',
                'status' => 'active',
                'ai_raw_response' => json_encode(['message' => 'Roadmap generated by AI for Flutter mobile development.']),
            ],
            [
                'user_id' => 2, // Budi (punya 2 roadmap)
                'skill_id' => 10, // Docker
                'title' => 'DevOps dengan Docker',
                'description' => 'Belajar containerization menggunakan Docker untuk deployment aplikasi.',
                'level' => 'Intermediate',
                'hours_per_day' => 1.5,
                'target_deadline' => '2026-04-30',
                'tujuan_akhir' => 'Mampu mengkontainerisasi aplikasi dan membuat Docker Compose untuk multi-service.',
                'status' => 'active',
                'ai_raw_response' => json_encode(['message' => 'Roadmap generated by AI for Docker DevOps learning.']),
            ],
            [
                'user_id' => 5, // Dewi
                'skill_id' => 8, // Python Data Science
                'title' => 'Data Science dengan Python',
                'description' => 'Roadmap lengkap belajar data science menggunakan Python, pandas, numpy, dan scikit-learn.',
                'level' => 'Beginner',
                'hours_per_day' => 3,
                'target_deadline' => '2026-08-01',
                'tujuan_akhir' => 'Mampu melakukan analisis data dan membuat model machine learning sederhana.',
                'status' => 'active',
                'ai_raw_response' => json_encode(['message' => 'Roadmap generated by AI for Python Data Science learning path.']),
            ],
        ];

        foreach ($roadmaps as $roadmap) {
            Roadmap::create($roadmap);
        }
    }
}
